### ISSUE TITLE
Mails get rejected

### ISSUE THREAD

**Issue by 0xErnie** [jdelic/opensmtpd-plusdashfilter#2]
Now that the loading of the filter seems to be working, I got a new error.

```
 -> RCPT TO:<alex-test@example.org>
<** 550 Invalid recipient
```

excerpts from my smtpd.conf:

```
filter pplusdash plusdash
listen on localhost filter pplusdash
accept from any for domain "example.org" virtual <aliases> deliver to mbox
```

Mails to alex+test@ and alex@ get delivered.

**edit:** I created a gist for the debug output of _smtpd -dv -T all_ during the session: 
https://gist.github.com/0xErnie/9959fc2cc1a6bc204a199675f0678fbe

**Comment by jdelic** [comment]
Unfortunately, I have bad news for you. It turns out that the approach I took in this filter will never work, since as far as I can tell, the filter API does not allow filters to modify smtp envelope data. The modification just gets thrown away. As I mentioned in #1, I haven't yet moved this into production and while looking into your issue, I figured out that my configuration works for an entirely different reason:

When you use a database backend for the user table, OpenSMTPD will query the `query_alias` query already for envelope addresses to validate recipients. I'm using a PostgreSQL database with a stored procedure to validate user email addresses and lookup email aliases. That code reads like this:

``` sql
CREATE OR REPLACE FUNCTION authserver_resolve_alias(email varchar) RETURNS varchar AS $$
DECLARE
    user_mailprefix varchar;
    user_domain varchar;
    primary_email varchar;
BEGIN
    SELECT split_part(email, '@', 1) INTO user_mailprefix;
    SELECT split_part(email, '@', 2) INTO user_domain;

    -- handle dashext by resolving it to plusext
    IF position('-' in user_mailprefix) > 0 THEN
        user_mailprefix := split_part(user_mailprefix, '-', 1) || '+' ||
                           split_part(user_mailprefix, '-', 2);
    END IF;

    -- handle plusext by cutting it and querying aliases
    IF position('+' in user_mailprefix) > 0 THEN
        user_mailprefix := split_part(user_mailprefix, '+', 1);
    END IF;

    SELECT primary_alias.mailprefix || '@' || primary_domain.name INTO primary_email FROM
            mailauth_emailalias AS "alias",
            mailauth_domain AS "domain",
            mailauth_emailalias AS "primary_alias",
            mailauth_domain AS "primary_domain",
            mailauth_mnuser AS "user"
        WHERE
            "primary_alias".user_id="user".uuid AND
            "primary_domain".id="primary_alias".domain_id AND
            "user".delivery_mailbox_id="primary_alias".id AND
            "user".uuid="alias".user_id AND
            "alias".domain_id="domain".id AND
            "alias".mailprefix=user_mailprefix AND
            "domain".name=user_domain;

    IF primary_email = email THEN
        RETURN 'virtmail';  -- primary email aliases are directed to delivery
    ELSE
        RETURN primary_email;
    END IF;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;
```

in smtpd.conf:

```
[...]
table validrecipients postgres:/etc/smtpd/postgresql.table.conf
[...]
accept from any for domain <validdomains> virtual <validrecipients> \
    deliver to mda procmail as virtmail
```

and in /etc/smtpd/postgresql.table.conf:

```
query_alias          SELECT * FROM authserver_resolve_alias($1);
```

As you can see, that setup already handles dashext and plusext, so my filter faithfully did a noop and then the table config took care of the actual handling. Sorry, for getting your hopes up by pushing this to GitHub :(.

With Debian you're probably out of luck right now since the published `OpenSMTPD-extras` packages in `backports` and `stretch` don't yet have the `table-python` binding. Using that and a simple Python script seems to be the easiest solution to actually fix this problem using similar logic as described above, until the changes mentioned by poolpOrg in https://github.com/OpenSMTPD/OpenSMTPD/issues/476 make their way upstream. I opened https://github.com/OpenSMTPD/OpenSMTPD/issues/729 to see if there is any other way of solving this right now.
